
# logger options
image_save_iter: 500        # How often do you want to save output images during training
image_display_iter: 500       # How often do you want to display output images during training
display_size: 1              # How many images do you want to display each time
snapshot_save_iter: 10000     # How often do you want to save trained models
log_iter: 10                  # How often do you want to log the training stats
#validation_iter: 2   # --> if you want to do evaluation in a fixed interval and not every epoch

# optimization options
max_iter: 1              # maximum number of training iterations
batch_size: 4                 # batch size
weight_decay: 0.0001          # weight decay
beta1: 0.5                    # Adam parameter
beta2: 0.999                  # Adam parameter
init: kaiming                 # initialization [gaussian/kaiming/xavier/orthogonal]
lr: 1e-04
lr_to_noise: 1e-04            # different learning rate for parameters leading to noise
lr_policy: step               # learning rate scheduler
step_size: 100000             # how often to decay learning rate
gamma: 0.5                    # how much to decay learning rate

loss_weights:
  reconstruction: 0.1
  discriminator: 1

regularization:
  d_interval: 16
  r1_weight: 10

# model options
latent_size: 512


# data options
input_dim: 3                                # number of image channels [1/3]
num_workers: 20                              # number of data loading threads
image_size: 256                               # first resize the shortest image side to this size
downsample_size: 256
extend_noise_with_random: True
